[tool.poetry]
name = "django-30-todo"
version = "0.1.0"
description = ""
authors = ["Rifqi Rosyidi <rief.rosyidi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
